# Generated by Django 5.0.7 on 2024-07-22 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.brand"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("engine_size", models.DecimalField(decimal_places=1, max_digits=10)),
                ("image_url", models.URLField()),
                ("gearbox", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                ("mileage", models.PositiveIntegerField()),
                ("seats", models.PositiveIntegerField()),
                ("doors", models.PositiveIntegerField()),
                ("body_type", models.CharField(max_length=50)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.carmodel"
                    ),
                ),
            ],
        ),
    ]
