# Generated by Django 5.0.7 on 2024-07-20 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_carmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fuel_type", models.CharField(max_length=50)),
                ("engine_size", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.carmodel"
                    ),
                ),
            ],
        ),
    ]
