# Generated by Django 5.0.7 on 2024-07-20 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_trim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trim",
            name="price",
        ),
        migrations.AddField(
            model_name="trim",
            name="potential_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField()),
                ("color", models.CharField(max_length=50)),
                ("registration_year", models.PositiveIntegerField()),
                ("mileage", models.PositiveIntegerField()),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.carmodel"
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars.trim"
                    ),
                ),
            ],
        ),
    ]
