# Generated by Django 5.0.7 on 2024-07-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_remove_trim_price_trim_potential_price_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trim",
            name="engine_size",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name="trim",
            name="potential_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
