# Generated by Django 5.0.7 on 2024-07-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_featuredcar"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
