# Generated by Django 5.0.7 on 2024-07-30 22:35

import nanoid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_car_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="hash",
            field=nanoid_field.fields.NanoidField(
                alphabet="1234567890ABCDEF", max_length=10
            ),
        ),
    ]
