# Generated by Django 5.0.7 on 2024-07-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_trim_engine_size_alter_trim_potential_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="trim",
        ),
        migrations.DeleteModel(
            name="Trim",
        ),
    ]
