# Generated by Django 5.0.7 on 2024-07-30 22:46

import nanoid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_car_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="hash",
            field=nanoid_field.fields.NanoidField(
                alphabet="1234567890ABCDEF", editable=False, max_length=10
            ),
        ),
    ]
