# Generated by Django 5.0.7 on 2024-07-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0009_bodytype_created_at_bodytype_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredcar",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="bodytype",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="brand",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
