# Generated by Django 5.0.7 on 2024-08-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0010_remove_featuredcar_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bodytype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="carmodel",
            options={"ordering": ["name"]},
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["car_model"], name="cars_car_car_mod_eb9880_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["body_type"], name="cars_car_body_ty_3059cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["price"], name="cars_car_price_f6b08b_idx"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(fields=["year"], name="cars_car_year_fc6735_idx"),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["is_available"], name="cars_car_is_avai_697038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["created_at"], name="cars_car_created_f3c7e2_idx"
            ),
        ),
    ]
