repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(alembic/|docs/)
      - id: end-of-file-fixer
        exclude: ^(alembic/|docs/)
      - id: check-added-large-files
        exclude: ^(alembic/|docs/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        exclude: alembic/
      - id: ruff-format
        exclude: alembic/
