# Generated by Django 5.0.7 on 2024-07-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customer_dni"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="user_id",
            new_name="user",
        ),
    ]
