# Generated by Django 5.0.7 on 2024-07-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_is_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
    ]
