# Generated by Django 5.0.7 on 2024-07-31 21:47

import nanoid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hash",
            field=nanoid_field.fields.NanoidField(
                alphabet="1234567890ABCDEF", editable=False, max_length=10
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="hash",
            field=nanoid_field.fields.NanoidField(
                alphabet="1234567890ABCDEF", editable=False, max_length=10
            ),
        ),
    ]
