# Generated by Django 5.0.7 on 2024-07-31 02:39

import nanoid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_rename_pdf_invoice_pdf_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="hash",
            field=nanoid_field.fields.NanoidField(
                alphabet="1234567890ABCDEF", editable=False, max_length=10
            ),
        ),
    ]
