# Generated by Django 5.0.7 on 2024-07-31 21:56

import nanoid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_invoice_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="hash",
            field=nanoid_field.fields.NanoidField(
                alphabet="1234567890ABCDEF", editable=False, max_length=10
            ),
        ),
    ]
