# Generated by Django 5.0.7 on 2024-07-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_invoice_created_at_invoice_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
