# Generated by Django 5.0.7 on 2024-07-31 23:04

import nanoid_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_invoice_created_at_alter_payment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="hash",
            field=nanoid_field.fields.NanoidField(
                alphabet="1234567890ABCDEF", editable=False, max_length=10
            ),
        ),
    ]
