# Generated by Django 5.0.7 on 2024-08-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0011_alter_bodytype_options_alter_carmodel_options_and_more"),
        ("sales", "0008_payment_hash"),
        ("users", "0003_rename_user_id_customer_user_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["sale"], name="sales_invoi_sale_id_470fd6_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["date"], name="sales_invoi_date_c3bcec_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["created_at"], name="sales_invoi_created_a99f6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["updated_at"], name="sales_invoi_updated_496b19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["sale"], name="sales_payme_sale_id_b07c2a_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["method"], name="sales_payme_method__267df3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["date"], name="sales_payme_date_23904f_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="sales_payme_created_0df64f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["updated_at"], name="sales_payme_updated_274cde_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["car"], name="sales_sale_car_id_4e5ce2_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer"], name="sales_sale_custome_f0dcab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["date"], name="sales_sale_date_ca4177_idx"),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["created_at"], name="sales_sale_created_e208b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["updated_at"], name="sales_sale_updated_edeb53_idx"
            ),
        ),
    ]
