name: CI

on:
  push:
    branches: ["master", "develop", "production"]
  pull_request:
    branches: ["master", "develop", "production"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements/local.txt

      - name: Run tests
        run: |
          pytest

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
